version: '1.0'

services:
  local-dev:
    build:
      context: ./
      dockerfile: ./Dockerfile.pytorch
      shm_size: '64gb'
    shm_size: '64gb'
    
    ports:
      - "10088:8888"
      - "10089:8889"
      - '10090:8890'
    runtime: nvidia
    volumes:
      - ~/dev/:/root/dev/
      - /data/:/data/
    command: tail -f 